"""identity organizations and tenancy

Revision ID: b6bdf8a6370e
Revises: 0001_initial_empty
Create Date: 2026-09-26 20:21:55.746491
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b6bdf8a6370e"
down_revision: str | None = "0001_initial_empty"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_organizations_name_nonempty"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pending_identity_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("csrf_secret", sa.LargeBinary(length=32), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("normalized_email", sa.String(length=320), nullable=True),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "octet_length(csrf_secret) = 32", name="ck_pending_identity_sessions_csrf_length"
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32", name="ck_pending_identity_sessions_hash_length"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_pending_identity_sessions_token_hash"),
    )
    op.create_index(
        "ix_pending_identity_sessions_identity_expiry",
        "pending_identity_sessions",
        ["issuer", "subject", "absolute_expires_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("normalized_email", sa.String(length=320), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name="ck_users_status"),
        sa.CheckConstraint(
            "(email_verified_at IS NULL AND normalized_email IS NULL) OR "
            "(email_verified_at IS NOT NULL AND normalized_email IS NOT NULL)",
            name="ck_users_verified_email_pair",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_status", "users", ["status"], unique=False)
    op.create_index(
        "uq_users_normalized_verified_email",
        "users",
        ["normalized_email"],
        unique=True,
        postgresql_where=sa.text("email_verified_at IS NOT NULL AND normalized_email IS NOT NULL"),
    )
    op.create_table(
        "external_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_authenticated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "length(issuer) > 0 AND length(subject) > 0", name="ck_external_identity_nonempty"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject", name="uq_external_identity_issuer_subject"),
    )
    op.create_index(
        "ix_external_identities_user_id", "external_identities", ["user_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('OWNER','ADMIN','MANAGER','TECHNICIAN','VIEWER')", name="ck_memberships_role"
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUSPENDED','REMOVED')", name="ck_memberships_status"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memberships_organization_status_role",
        "memberships",
        ["organization_id", "status", "role"],
        unique=False,
    )
    op.create_index(
        "ix_memberships_user_status", "memberships", ["user_id", "status"], unique=False
    )
    op.create_index(
        "uq_memberships_user_organization_not_removed",
        "memberships",
        ["user_id", "organization_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'REMOVED'"),
    )
    op.create_table(
        "operator_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("operator_label", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("target_organization_id", sa.UUID(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action_type IN ('BOOTSTRAPPED','ORGANIZATION_PROVISIONED','USER_DISABLED',"
            "'USER_ENABLED','IDENTITY_LINKED','OWNER_SUCCESSION','OWNER_RECOVERED')",
            name="ck_operator_actions_type",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(details) = 'object'", name="ck_operator_actions_details_object"
        ),
        sa.ForeignKeyConstraint(
            ["target_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_id", name="uq_operator_actions_operation_id"),
    )
    op.create_index(
        "ix_operator_actions_target_organization",
        "operator_actions",
        ["target_organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_operator_actions_target_user", "operator_actions", ["target_user_id"], unique=False
    )
    op.create_index(
        "ix_operator_actions_type_created",
        "operator_actions",
        ["action_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "application_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("csrf_secret", sa.LargeBinary(length=32), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("external_identity_id", sa.UUID(), nullable=False),
        sa.Column("auth_email", sa.String(length=320), nullable=True),
        sa.Column(
            "auth_email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "octet_length(csrf_secret) = 32", name="ck_application_sessions_csrf_length"
        ),
        sa.CheckConstraint(
            "octet_length(session_token_hash) = 32", name="ck_application_sessions_hash_length"
        ),
        sa.ForeignKeyConstraint(
            ["external_identity_id"], ["external_identities.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token_hash", name="uq_application_sessions_token_hash"),
    )
    op.create_index(
        "ix_application_sessions_absolute_expires",
        "application_sessions",
        ["absolute_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_application_sessions_last_seen", "application_sessions", ["last_seen_at"], unique=False
    )
    op.create_index(
        "ix_application_sessions_user_revoked",
        "application_sessions",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "installation_state",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("initial_organization_id", sa.UUID(), nullable=False),
        sa.Column("initial_user_id", sa.UUID(), nullable=False),
        sa.Column("initial_external_identity_id", sa.UUID(), nullable=False),
        sa.Column("organization_name", sa.String(length=200), nullable=False),
        sa.Column(
            "initialized_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("singleton_id = 1", name="ck_installation_state_singleton"),
        sa.ForeignKeyConstraint(
            ["initial_external_identity_id"], ["external_identities.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["initial_organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["initial_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("singleton_id"),
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("creator_membership_id", sa.UUID(), nullable=False),
        sa.Column("accepted_user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('ADMIN','MANAGER','TECHNICIAN','VIEWER')", name="ck_invitations_role"
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','ACCEPTED','REVOKED','EXPIRED')", name="ck_invitations_status"
        ),
        sa.ForeignKeyConstraint(["accepted_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["creator_membership_id"], ["memberships.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_invitations_token_hash"),
    )
    op.create_index("ix_invitations_expires_at", "invitations", ["expires_at"], unique=False)
    op.create_index(
        "ix_invitations_organization_status_created",
        "invitations",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_invitations_pending_org_email",
        "invitations",
        ["organization_id", "normalized_email"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "invitation_acceptance_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invitation_id", sa.UUID(), nullable=False),
        sa.Column("application_session_id", sa.UUID(), nullable=True),
        sa.Column("pending_identity_session_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(application_session_id IS NULL) <> (pending_identity_session_id IS NULL)",
            name="ck_invitation_attempt_exact_session",
        ),
        sa.ForeignKeyConstraint(
            ["application_session_id"], ["application_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["invitation_id"], ["invitations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["pending_identity_session_id"], ["pending_identity_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invitation_attempt_application_session",
        "invitation_acceptance_attempts",
        ["application_session_id"],
        unique=False,
    )
    op.create_index(
        "ix_invitation_attempt_invitation_consumed",
        "invitation_acceptance_attempts",
        ["invitation_id", "consumed_at"],
        unique=False,
    )
    op.create_index(
        "ix_invitation_attempt_pending_session",
        "invitation_acceptance_attempts",
        ["pending_identity_session_id"],
        unique=False,
    )
    op.create_table(
        "oidc_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("state_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("nonce_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("pkce_verifier", sa.Text(), nullable=True),
        sa.Column("browser_binding_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("expected_issuer", sa.Text(), nullable=True),
        sa.Column("return_to", sa.String(length=500), nullable=True),
        sa.Column("invitation_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(kind = 'LOGIN' AND ((consumed_at IS NULL AND nonce_hash IS NOT NULL "
            "AND pkce_verifier IS NOT NULL AND browser_binding_hash IS NOT NULL "
            "AND expected_issuer IS NOT NULL) OR (consumed_at IS NOT NULL "
            "AND nonce_hash IS NULL AND pkce_verifier IS NULL "
            "AND browser_binding_hash IS NULL))) OR (kind = 'LOGOUT' "
            "AND nonce_hash IS NULL AND pkce_verifier IS NULL "
            "AND browser_binding_hash IS NULL)",
            name="ck_oidc_transactions_kind_fields",
        ),
        sa.CheckConstraint("kind IN ('LOGIN','LOGOUT')", name="ck_oidc_transactions_kind"),
        sa.ForeignKeyConstraint(["invitation_id"], ["invitations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash", name="uq_oidc_transactions_state_hash"),
    )
    op.create_index(
        "ix_oidc_transactions_expires", "oidc_transactions", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_oidc_transactions_expires", table_name="oidc_transactions")
    op.drop_table("oidc_transactions")
    op.drop_index(
        "ix_invitation_attempt_pending_session", table_name="invitation_acceptance_attempts"
    )
    op.drop_index(
        "ix_invitation_attempt_invitation_consumed", table_name="invitation_acceptance_attempts"
    )
    op.drop_index(
        "ix_invitation_attempt_application_session", table_name="invitation_acceptance_attempts"
    )
    op.drop_table("invitation_acceptance_attempts")
    op.drop_index(
        "uq_invitations_pending_org_email",
        table_name="invitations",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_invitations_organization_status_created", table_name="invitations")
    op.drop_index("ix_invitations_expires_at", table_name="invitations")
    op.drop_table("invitations")
    op.drop_table("installation_state")
    op.drop_index("ix_application_sessions_user_revoked", table_name="application_sessions")
    op.drop_index("ix_application_sessions_last_seen", table_name="application_sessions")
    op.drop_index("ix_application_sessions_absolute_expires", table_name="application_sessions")
    op.drop_table("application_sessions")
    op.drop_index("ix_operator_actions_type_created", table_name="operator_actions")
    op.drop_index("ix_operator_actions_target_user", table_name="operator_actions")
    op.drop_index("ix_operator_actions_target_organization", table_name="operator_actions")
    op.drop_table("operator_actions")
    op.drop_index(
        "uq_memberships_user_organization_not_removed",
        table_name="memberships",
        postgresql_where=sa.text("status <> 'REMOVED'"),
    )
    op.drop_index("ix_memberships_user_status", table_name="memberships")
    op.drop_index("ix_memberships_organization_status_role", table_name="memberships")
    op.drop_table("memberships")
    op.drop_index("ix_external_identities_user_id", table_name="external_identities")
    op.drop_table("external_identities")
    op.drop_index(
        "uq_users_normalized_verified_email",
        table_name="users",
        postgresql_where=sa.text("email_verified_at IS NOT NULL AND normalized_email IS NOT NULL"),
    )
    op.drop_index("ix_users_status", table_name="users")
    op.drop_table("users")
    op.drop_index(
        "ix_pending_identity_sessions_identity_expiry", table_name="pending_identity_sessions"
    )
    op.drop_table("pending_identity_sessions")
    op.drop_table("organizations")
    # ### end Alembic commands ###
